version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
platform:
- x86
- x64
build:
  verbosity: minimal
artifacts:
- path: Debug
  name: Reactofus-dbg-MSVC-x86
- path: x64/Debug
  name: Reactofus-dbg-MSVC-x64
- path: ARM/Debug
  name: Reactofus-dbg-MSVC-ARM