version: 1.0.{build}
image: Visual Studio 2017
configuration: Debug
platform:
- x86
- x64
build:
  verbosity: minimal
artifacts:
- path: build/x86
  name: Reactofus-MSVC-x86
- path: build/x64
  name: Reactofus-MSVC-x64
- path: build/ARM
  name: Reactofus-MSVC-ARM